# Use official lightweight PostgreSQL Alpine image
FROM postgres:15-alpine3.20

# Upgrade vulnerable base packages
Run apk update && apk upgrade && \
	apk add --no-cache icu openssl

# Copy initialization SQL script into Docker's entrypoint directory
COPY ./podverse_db/init_db.sql /docker-entrypoint-initdb.d/

# Expose PostgreSQL port (default 5432)
EXPOSE 5432

# NOTE:
# Initialization scripts in /docker-entrypoint-initdb.d/ run ONLY on fresh DB volumes.
# To re-run the script, you must remove the PostgreSQL data volume.