version: "3.9"

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    image: podverse-database:latest
    container_name: podverse_database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - podverse-network

  redis:
    image: redis/redis-stack:latest
    container_name: podverse_redis
    ports:
      - "6380:6379"
    networks:
      - podverse-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: podverse-backend:latest
    container_name: podverse_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
      - ./backend/.env
    environment:
      FLASK_APP: main.py
      FLASK_ENV: ${FLASK_ENV}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      REDIS_RESULT_BACKEND: ${REDIS_RESULT_BACKEND}
    volumes:
      - ./backend/app:/app/app
      - ./backend/scripts:/app/scripts
      - ./backend/exports:/app/exports
    depends_on:
      - database
      - redis
    networks:
      - podverse-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: podverse-backend:latest
    container_name: podverse_celery
    entrypoint: ""  # override entrypoint.sh
    command: celery -A make_celery worker --loglevel=info
    env_file:
      - ./backend/.env
    environment:
      FLASK_APP: main.py
      FLASK_ENV: ${FLASK_ENV}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      REDIS_RESULT_BACKEND: ${REDIS_RESULT_BACKEND}
    depends_on:
      - database
      - redis
      - backend
    volumes:
      - ./backend/app:/app/app
      - ./backend/scripts:/app/scripts
      - ./backend/exports:/app/exports
    networks:
      - podverse-network

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: podverse-backend:latest
    container_name: podverse_celery_beat
    entrypoint: ""  # override entrypoint.sh
    command: celery -A make_celery beat --loglevel=info
    env_file:
      - ./backend/.env
    environment:
      FLASK_APP: main.py
      FLASK_ENV: ${FLASK_ENV}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      REDIS_RESULT_BACKEND: ${REDIS_RESULT_BACKEND}
    depends_on:
      - database
      - redis
      - backend
      - celery
    volumes:
      - ./backend/app:/app/app
      - ./backend/scripts:/app/scripts
      - ./backend/exports:/app/exports
    networks:
      - podverse-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: podverse_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    networks:
      - podverse-network

volumes:
  pgdata:

networks:
  podverse-network:
    driver: bridge